name: Workflow Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
    - cron: "0 */1 * * *"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "test test"
